# Generated by Django 3.1.6 on 2021-02-09 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0002_auto_20210208_2247'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SPO2_Data',
            new_name='RR',
        ),
        migrations.RenameModel(
            old_name='Temperature_Data',
            new_name='SPO2',
        ),
        migrations.RenameModel(
            old_name='RR_Data',
            new_name='Temperature',
        ),
    ]
