# Generated by Django 3.1.6 on 2021-02-13 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0003_auto_20210209_1909'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Temperature',
            new_name='Temp',
        ),
    ]
