# Generated by Django 3.1.7 on 2021-02-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0005_senior_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='senior',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
