# Generated by Django 3.1.7 on 2021-03-06 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0006_senior_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rr',
            name='value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='spo2',
            name='value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='temp',
            name='value',
            field=models.FloatField(),
        ),
    ]
